### ISSUE TITLE
An error occurred when launching

### ISSUE THREAD

**Issue by hoginwang** [gilmarsquinelato/i18n-manager#153]
![image](https://user-images.githubusercontent.com/4257672/60729817-2ce9fc00-9f76-11e9-9873-3974b3d8bb09.png)

**Comment by gilmarsquinelato** [comment]
Hi, could be a good thing to understand better, what is the version that you are using, what is the steps to reproduce this error. If is prévios than the v2.0 I would like that you download the new version and try again.

**Comment by hoginwang** [comment]
It's v2.0. After the installation finished and the app launch automatically, the error appeared.

I tried to uninstall and reinstall. The error still appeared.

**Comment by gilmarsquinelato** [comment]
Hi @hoginwang, I just released the v2.0.1, this released have a bugfix related with Google Translate, but I also did a small refactoring in the app menu, that apparently is the cause of your error.
Could you test this version to check if the bug was solved?

**Comment by hoginwang** [comment]
![image](https://user-images.githubusercontent.com/4257672/60768728-1d93bb80-a0fa-11e9-9a83-01069e82ac17.png)

After open the v2.0.1, no error warning but nothing shows.

**Comment by gilmarsquinelato** [comment]
Released v2.0.2, changed the way to open the html file in the release build, hope this works :D

**Comment by hoginwang** [comment]
It's still blank with v2.0.2.😥

**Comment by gilmarsquinelato** [comment]
Can you try the v2.0.3? 😊

**Comment by hoginwang** [comment]
It's still blank v2.0.3.... 😯

**Comment by gilmarsquinelato** [comment]
Just released the v2.0.4.
This version I disabled the initial redirect.
If this doesn't work, I'll need to change the routing library, that seems to be the problem, as already reported in some electron issues.

**Comment by ohager** [comment]
@gilmarsquinelato On https://electronjs.org/apps/i18n-manager is still 2.0.2 and I'm facing the same blank screen issue like @hoginwang

**Comment by ohager** [comment]
Still blank screen with 2.0.4. Being on Ubuntu 18 using AppImage

**Comment by ohager** [comment]
Fallback to 2.0.1 - this version works

**Comment by hoginwang** [comment]
Still blank with 2.0.4😅

**Comment by atwright147** [comment]
Broken for me too.

i18n Manager v2.0.4  (I also tried v2.0.2 first, which was broken too)
macOS 10.14.5

**Comment by gilmarsquinelato** [comment]
> @gilmarsquinelato On https://electronjs.org/apps/i18n-manager is 2.0.2 and I'm facing the same blank screen issue like @hoginwang... will try newest version now.

@ohager these versions weren't appearing in the electron website because they are pre-release versions.

I just release v2.0.5, this version I changed the router library to react-router because the @react/router doesn't support hash history.

Browser history is a known problem being reported in some issues in the electron repo, and the solution is to change to hash history.

I don't know if this will solve the blank screen problem, but I hope that works :D

**Comment by ohager** [comment]
@gilmarsquinelato It works now.

@atwright147 @hoginwang ^^^

**Comment by hoginwang** [comment]
It works with 2.0.5.👌😊

**Comment by gilmarsquinelato** [comment]
@hoginwang are you opening the testData folder of the repo for testing purposes?

**Comment by hoginwang** [comment]
@gilmarsquinelato Nope. I just open my own project folder. If I click on the Recent folder link at the index page, the edit page appeared but nothing in it. I have to Ctrl+O to open the folder. And no right click menu. So I still use 1.8.2 to continue my jobs after I tested 2.0.x.

**Comment by gilmarsquinelato** [comment]
@hoginwang the file grouping algorithm has changed, look at the release notes of the v2.0.0 to understand better, and look at the structures of testData folder and open it as well.

Also, send some screenshots to better understand how your folder is being displayed in the app and where you are trying to get the context menu based on the provided screenshot. I think with these informations I can help you better.

And another thing, open a new issue with the previous informations, because this issue is related a bug, that now is solved. This will keep the issues better organized 😁.
