### ISSUE TITLE
Context menu doesn't appear

### ISSUE THREAD

**Issue by hoginwang** [gilmarsquinelato/i18n-manager#167]
![ScreenToGif_18](https://user-images.githubusercontent.com/4257672/61269942-b4cfd180-a7d2-11e9-8d72-81d6729e91aa.gif)

Right click on the keys, but the context menu doesn't appear.

![image](https://user-images.githubusercontent.com/4257672/61269885-88b45080-a7d2-11e9-8c1c-3738a83a56d3.png)
![image](https://user-images.githubusercontent.com/4257672/61270052-142de180-a7d3-11e9-82bf-07fab9c05264.png)

Failed with testData folder and my own folder.

v2.0.5

**Comment by gilmarsquinelato** [comment]
@hoginwang I tested the context menu using the folder you provided me, and everything is working fine, and I didn't receive any report related to the context menu, can you check it in another computer or OS?

**Comment by czytelny** [comment]
Same here, tested on macOS. I'll try to build it locally and check what's the root cause

**Comment by gilmarsquinelato** [comment]
@czytelny I appreciate your help :D
I downloaded the release version (v2.0.5) and used it, but it is working fine in my machine, I think that is the IPC that isn't sending the messages correctly to the main thread.

**Comment by gilmarsquinelato** [comment]
Hey guys, I released the [v2.0.6](https://github.com/gilmarsquinelato/i18n-manager/releases/tag/2.0.6) that allows us to open dev tools even in production mode by just adding an environment variable (ELECTRON_IS_DEV) when opening the app.

**Comment by gilmarsquinelato** [comment]
Hey guys, can someone confirm if the error persists in the v2.0.6, I tried on another computer and the error didn't occur.

**Comment by gilmarsquinelato** [comment]
Due to the lack of response, I'll close this issue.
If the problem persists in future releases, please reopen this issue.

**Comment by czytelny** [comment]
Unfortunately opening app v2.0.6 with ELECTRON_IS_DEV results in white screen, no console logs, no network traffic - just nothing. So can't really debug this. Tried to refresh (cmd+r) - same result.
<img width="1136" alt="Screenshot 2019-08-15 at 20 24 15" src="https://user-images.githubusercontent.com/5399256/63116867-f05ce780-bf9a-11e9-8e8f-8129f909f403.png">

**Comment by gilmarsquinelato** [comment]
And just opening it normal, without environment variables on that version?

**Comment by czytelny** [comment]
Opening without env results with working program although context menu isn't working. 

But I have good news: I fetched most recent version, compiled, run and discovered error in console log:

<img width="1136" alt="Screenshot 2019-08-16 at 18 52 04" src="https://user-images.githubusercontent.com/5399256/63184251-3b3c3500-c057-11e9-91c7-9e6641235c07.png">

Now the good thing is that commenting line 54 in saga.ts: 
```
///  yield takeLatest(actions.ACTION_TYPES.LOAD_SUPPORTED_LANGUAGES, loadSupportedLanguages);
```

Fix both: lack of context menu and this one (because it's still not working on 2.0.6) https://github.com/gilmarsquinelato/i18n-manager/issues/166


I don't have time now for digging to root cause of this crash, but hopefully it helped!

**Comment by gilmarsquinelato** [comment]
@czytelny oh man, thanks a lot!
The problem is that probably the provided key to translate api is invalid, because the returned status code is 403 (unauthorised).
I can solve this now, just handle that error.
I'll release the 2.0.7 with this fix and allow to use the dev tools even in released package without the environment variable.

Thanks a lot for your help!

**Comment by marscosta** [comment]
Hello,

First of all thank you for the super useful tool.

403 can also be related to the fact that a proxy is required to reach the specific server. So, if it would be possible to either:
 - add a setting to use a specified proxy server for connections, or,
 - use the environmental variables (HTTP_PROXY for example) that already exist for the same effect (similar to what npm and git does).

The problem could be solved.

**Comment by gilmarsquinelato** [comment]
Hi @marscosta,

Thanks!
This is really helpful!

I'm trying to back to maintain this tool, but the last months was really busy. I'm planning to develop the v2.1 of this tool fixing all currently opened issues.

**Comment by gilmarsquinelato** [comment]
Created a feature issue #256

**Comment by gilmarsquinelato** [comment]
Hi @hoginwang, @czytelny and @marscosta, the v3.0 was released!

This version has a brand new context menu so this issue certainly was fixed.
About the proxy, the electron uses the system proxy settings, so we don't need to do anything.
