### ISSUE TITLE
Multi-line text-boxes

### ISSUE THREAD

**Issue by jeremy-holt** [gilmarsquinelato/i18n-manager#331]
1) I've started using yaml because of the ability to have multiline text. It would be great if the text boxes could be multiline as well.

2) It would be really useful to have full text search instead of being limited just to the keys

3) Once the translation has been done, I think the box should just close without having to click OK

Also, out of curiosity, why does the app insert the `>-` symbol for multiline? It doesn't seem to be necessary.

+1 for the feature request for the filewatcher
+1 for the feature request for filtering by new entries

**Comment by gilmarsquinelato** [comment]
Hey @jeremy-holt, thanks for the issue.

1. The multiline support is already implemented in v3 that it's in development.

2. Fulltext search in the values are very expensive tasks, and this can impact a lot in the performance, think about projects that have thousands of translation keys, they will have their UIs frozen until the search finishes.

3. I decided to keep the translation panel opened after it's finished because we can have errors during the translation process like the field of the source language is empty, or the API doesn't support the given language, or something went wrong when calling the translation API.

About the strange symbol, with the new multiline text fields, this symbol has gone with the proper symbol of multiline.

The file watcher is the biggest feature of this release and is pending to develop yet.
The filtering will be even more powerful, you will be able to filter the keys by its state (All, Modified, New, Error)

**Comment by jeremy-holt** [comment]
Thanks for getting back to me.
1. Great
2. Noted
3. Perhaps it could close if there are no errors?

A couple of other things:
1. I've just moved my translation files from json to yaml.
It would be great if the app could check the validity of the yaml file. If the file is invalid it reports that all translations are missing - which is OK I suppose. Once I realized that the yaml was invalid, I installed a yaml linter in VS Code and catch the error before trying the translation.

2. A big +++ for implementing DeepLearning, or have a way to show alternative translations.
I'm going nuts translating into Portuguese "You have no stocks available" (as in stocks in a warehouse). It gets translated correctly into French, but to Portuguese Google insists that I'm talking about "ações".
The same goes for the word "bags" as in "You have 200 bags in the warehouse" - French is fine, Portuguese gets translated as "malas" or "sacolas".
I know that this is not a problem with the app, but being able to pick from alternative translations would be very very helpful.

Muito obrigado cara para uma aplicação excelente - eu uso o tempo tudo.
Abs
Jeremy (falo Portuguese!)

**Comment by jeremy-holt** [comment]
Oh - something else

Could I suggest that you add a warning dialog if the user clicks the "All Keys" radio by mistake while "Overwrite not empty fields" is checked - it is sooo easy to overwrite all the translations that have been manually changed!
![image](https://user-images.githubusercontent.com/2135027/72891753-dd4e0080-3d0c-11ea-9443-865638f0b363.png)

**Comment by gilmarsquinelato** [comment]
> Thanks for getting back to me.
> 
> 1. Great
> 2. Noted
> 3. Perhaps it could close if there are no errors?
> 
> A couple of other things:
> 
> 1. I've just moved my translation files from json to yaml.
>    It would be great if the app could check the validity of the yaml file. If the file is invalid it reports that all translations are missing - which is OK I suppose. Once I realized that the yaml was invalid, I installed a yaml linter in VS Code and catch the error before trying the translation.
> 2. A big +++ for implementing DeepLearning, or have a way to show alternative translations.
>    I'm going nuts translating into Portuguese "You have no stocks available" (as in stocks in a warehouse). It gets translated correctly into French, but to Portuguese Google insists that I'm talking about "ações".
>    The same goes for the word "bags" as in "You have 200 bags in the warehouse" - French is fine, Portuguese gets translated as "malas" or "sacolas".
>    I know that this is not a problem with the app, but being able to pick from alternative translations would be very very helpful.
> 
> Muito obrigado cara para uma aplicação excelente - eu uso o tempo tudo.
> Abs
> Jeremy (falo Portuguese!)

PT: ótimo!

Well, about the third point, yep, totally agree! Can you raise separate issues and link this one, so then we have single issues for each bug/feature 😄

**Comment by gilmarsquinelato** [comment]
> 1. I've just moved my translation files from json to yaml.
>    It would be great if the app could check the validity of the yaml file. If the file is invalid it reports that all translations are missing - which is OK I suppose. Once I realized that the yaml was invalid, I installed a yaml linter in VS Code and catch the error before trying the translation.


About the yaml parsing, I don't think that this will be possible at the moment, since the nature of vscode and i18n manager are different.

Like, vscode "just" opens your file, no matter if it's valid or not, and do its analysis over it.
But i18n manager does parsing and a lot of merging logic before rendering it, so to parse it and understand what keys the given file has, it need to be a valid file.

**Comment by gilmarsquinelato** [comment]
> Oh - something else
> 
> Could I suggest that you add a warning dialog if the user clicks the "All Keys" radio by mistake while "Overwrite not empty fields" is checked - it is sooo easy to overwrite all the translations that have been manually changed!

Cool, this is a UX improvement that is really needed.
Raise a separate issue for that pls?

**Comment by jeremy-holt** [comment]
OK - abri novos issues para o acima.

Voce esta em Londres? Legal - eu estou de Londres, morei 25 anos no Fortaleza, Sao Paulo, Castanhal (cou do mundo perto de Belem) e agora moro na Costa do Marfim.

Meu filho esta estudando no UCL..

Abracos
Jeremy

**Comment by gilmarsquinelato** [comment]
> OK - abri novos issues para o acima.
> 
> Voce esta em Londres? Legal - eu estou de Londres, morei 25 anos no Fortaleza, Sao Paulo, Castanhal (cou do mundo perto de Belem) e agora moro na Costa do Marfim.
> 
> Meu filho esta estudando no UCL..
> 
> Abracos
> Jeremy

Nossa! Top demais!
Sou do interior do Rio, e morei 5 anos em Campinas-SP

**Comment by gilmarsquinelato** [comment]
Hi @jeremy-holt, the v3.0 was released!
