### ISSUE TITLE
Feature Request: exclude token/match/regex

### ISSUE THREAD

**Issue by blankey1337** [gilmarsquinelato/i18n-manager#372]
Say I have a string like this:
"hello {name}"

I would like for "name" not to be translated. Currently I have to go back in and modify this after translation, which is tedious. Is there a better way? if not, maybe a feature to skip a token based on regex would be helpful.

**Comment by gilmarsquinelato** [comment]
Unfortunately, this is not possible due to some things:
* The translation engine now is only the Google Translate API, and we relly on its process, and it doesn't detect tokens.
* The tool now is agnostic about the tokens, since it aims to support any kind of tokenisation, and for supporting only `.json`, `.arb` and `.yaml` we have a lot of patterns to understand, one example is the ICU message format, that is the most common, that format has a very complex structure.
