### ISSUE TITLE
Cannot delete items

### ISSUE THREAD

**Issue by Androz2091** [gilmarsquinelato/i18n-manager#376]
Hello,
I'm trying to delete the `SEND_AWAIT_REPLY` key and it works, but when I use `CMD + S` to save, the key reappears. Looks like it's not deleted from the json file when the "Delete" button is pressed.
How to reproduce: https://streamable.com/3tjgxb
Also thank you for your great work!

**Comment by gilmarsquinelato** [comment]
Hey @Androz2091 thanks for the bug report
I'll analyse and release a bugfix as soon as I can

**Comment by Androz2091** [comment]
Looks like this happens when I rename a key... 🤔

**Comment by gilmarsquinelato** [comment]
It's related to the process of saving the files
To keep the keys sorted correctly, I needed to get the original file contents and merge with the new one.
But in that process, it didn't remove the not existing keys.
The solution was to create a custom merge function, that updates the existing ones and drops the removed/renamed keys.

The fix is coming today in v3.0.2

**Comment by Androz2091** [comment]
Oh, all right, perfect!

**Comment by gilmarsquinelato** [comment]
v3.0.2 released!

**Comment by gilmarsquinelato** [comment]
Can you check if it's working correctly in v3.0.2?

**Comment by Androz2091** [comment]
Yes, it's working perfectly, thank you!
