### ISSUE TITLE
Possibility to load/save json files using API

### ISSUE THREAD

**Issue by sixbras** [gilmarsquinelato/i18n-manager#381]
Hello, i looking for a tool to handle my i18n files, and i love your job, really well done.

I thinking to make it run online as a service, to give the opportunities to multiple translators to work on same files.

Another alternative can be to link json to the app with an endpoint api that can be defined in the settings. This way i18n json can be online and shared by multiple users.

**Comment by gilmarsquinelato** [comment]
Hi, @sixbras thanks!

The first thought when designing this tool was to make it a web app, but in the end, I decided to make it a desktop app, so I wouldn't need to handle and pay for a dedicated server.
Since this app is an open-source project, I don't earn any money with it, so it's difficult to make it available in a server.

The options to expose it through API isn't doable since most of the editing logic is handled in the UI.

A possibility is to make this tool to not be an electron app anymore and start to be a npm package or something like that starts a webserver.

**Comment by sixbras** [comment]
hi Gilmar , i totally understand your point of view.

I'm thinking to start a project similar to yours, that can run on node server.
If you don't mind i will, i will take inspiration from your project to get started. If I come up with something correct I will share it and I will not forget to mention the original idea.

**Comment by gilmarsquinelato** [comment]
Cool go on! 😄 

One downside about having a node server is that you can't keep the folder in sync with git every time.
What I recommend you is to analyse all the risks, pros and cons before putting effort on it.
