### ISSUE TITLE
[BUG] Windows alert

### ISSUE THREAD

**Issue by ARTWINPRO** [gilmarsquinelato/i18n-manager#395]
**Describe the bug**
Windows 10 Pro - Microsoft defender

**Expected behavior**
When we try to run i18n-manager on official installed windows, we see this alert from windows 10. Maybe you have some solution ? I think problem is "Publisher: Unknown"

**Screenshots**
![98186751_928100490968330_6434185983813484544_n](https://user-images.githubusercontent.com/16427316/82187996-dff4e700-98f5-11ea-9cad-5f438c122567.png)

**App version:** [e.g. 3.0.0]

**Desktop:**
 - OS: Windows 10 Pro
 - OS Version: -

**Additional context**
-

**Comment by gilmarsquinelato** [comment]
This is due to the application don't have an application signed certificate.
And this certificate is paid, and kind of expensive.

**Comment by ARTWINPRO** [comment]
> This is due to the application don't have an application signed certificate.
> And this certificate is paid, and kind of expensive.

Maybe we can find some solution together ? What the price, and how long its will be ?

**Comment by gilmarsquinelato** [comment]
The problem is that since this tool is totally free, and I don't have any earnings with it, don't worth it to pay for it.
And if we sign this application, we should sign it for every platform (Windows, Linux and Mac OS).
The prices are:
* Mac OS: $99 due to Apple Developer Program
* Windows: $179 using Comodo certificate

So like I said, doesn't worth it to pay this much for a tool that doesn't have any revenue to pay itself.

**Comment by gilmarsquinelato** [comment]
Remembering, this is not a problem, this is just a Windows Smart Screen telling you that this application doesn't have a certificate, it's not a virus 😄.

**Comment by ARTWINPRO** [comment]
@gilmarsquinelato 179$ - its for one pc or for all ?

**Comment by gilmarsquinelato** [comment]
For all.
And as I said, if we do for one, we should do for all the platforms, so wouldn't be only 179$.
And this amount is per year.
