### ISSUE TITLE
Add new language

### ISSUE THREAD

**Issue by turdwaster** [gilmarsquinelato/i18n-manager#402]
It would be really nice to be able to add a new language, especially for non-tech-savvy users. Perhaps file menu -> Add language or something, and you enter the code, i.e. "ru" and an empty ru.json/whatever is created (based on ending of currently opened file types). The rest already seems to be handled nicely as-is!

**Comment by gilmarsquinelato** [comment]
This feature was already requested, but I cannot do this since this tool supports more than one file and folder structure.
Enforcing a file structure wouldn't be a good way to do this since it would work for some and not work for others.

What I recommend is to just create an empty file with the desired name.
The tool is capable to recognize file changes from v3, so if you add it will appear automatically.

**Comment by turdwaster** [comment]
Ok, I get that it would be sort of messy then. If I happen to get a bright idea, I will whip up a PR for this. Thanks for the quick answer.
