### ISSUE TITLE
Can you please add the dependencies to your readme?

### ISSUE THREAD

**Issue by bphilipnyc** [gilmarsquinelato/i18n-manager#86]
Seems like at a minimum, you need `rimraf` and `concurrently` and of course, `yarn`. 

Getting an error and I'm not sure what other packages are required.  Sorry, a little new to front-end work, but lots of experience with programming.

```
sudo yarn start
yarn run v1.9.2
$ yarn clean && concurrently "yarn start:web" "yarn build:main && yarn start:main" "yarn watch:main"
$ rimraf build dist
$ ng serve
$ tsc --outDir ./build -w -p ./main
$ tsc --outDir ./build -d -p ./main
[0] /bin/sh: ng: command not found
```

**Comment by gilmarsquinelato** [comment]
Hello @bphilipnyc!
The problem that you related is because you don't have the Angular CLI.
After the app is running, it will show a white screen, you will need to reload (Ctrl/Cmd + R) after the angular finished to start the server.
Unfortunately, this is happening because of a task in the concurrently called wait-on is not detecting when the angular server is ready.
I'm looking for a way to solve that problem.

**Comment by gilmarsquinelato** [comment]
@bphilipnyc added the dependency of the Angular CLI in the README.
Thank you for the help!
